---

stages:
  - build
  - deploy

build:
  stage: build
  except:
    - tags
  image:
    name: frankhjung/haskell:9.2.8
    entrypoint: [""]
  variables:
    PROJECT: multiply
    RTSOPTS: +RTS -N1 -s
    STACK_ROOT: ${CI_PROJECT_DIR}/.stack-work
  script:
    - make setup clean check build test bench doc
    - mv $(stack path --local-install-root)/doc/${PROJECT}*/ public/
    - cp -fp ${STACK_ROOT}/benchmark.html public/
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - ${STACK_ROOT}

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  image: alpine:latest
  script:
    - echo Publish documentation ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
