---

name: haskell scrapbook

on:
  push:
    branches:
      - master
      - 'feature**'
  check_run:
    types: [rerequested, requested_action]

jobs:

  build:

    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v1.0.0
        with:
          ref: refs/heads/master
          fetch-depth: 1

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            .stack/
            .stack-work/
          key: $GITHUB_REF

      - name: setup
        run: |
          stack path
          stack setup

      - name: build
        run: |
          stack clean
          stack build --pedantic --no-test

      - name: test
        run: stack test

      - name: benchmark
        run: stack bench scrapbook:bench:multiplyBench --benchmark-arguments '-o .stack-work/benchmark-multiply.html'

      - name: document
        run: stack haddock --no-rerun-tests --no-reconfigure

      - name: copy
        run: |
          mv $(stack path --local-doc-root) public/
          mv .stack-work/benchmark-*.html public/

      - name: publish
        uses: crazy-max/ghaction-github-pages@v0.4.0
        if: success()
        with:
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
