---

name: haskell multiply

on:   # yamllint disable-line rule:truthy
  push:
    branches: ['master', 'feature*']
    tags-ignore: ['*']
  check_run:
    types: [rerequested, requested_action]

env:
  PROJECT: multiply
  STACK_ROOT: ${{ github.workspace }}/.stack

jobs:

  build:

    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STACK_ROOT }}
          key: ${{ github.ref }}

      - name: build
        run: stack build --pedantic --no-test

      - name: test
        run: stack test --coverage

      - name: bench
        run: stack bench --benchmark-arguments '-o ${{ env.STACK_ROOT }}/benchmark.html'

      - name: haddock
        if: github.ref == 'refs/heads/master'
        run: |
          stack haddock --no-haddock-deps
          mv $(stack path --local-install-root)/doc/${{ env.PROJECT }}*/ public/
          mv ${{ env.STACK_ROOT }}/benchmark.html public/

      - name: publish
        if: success() && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
